// Eke tiered hint generation — see EVENKEEL_BIBLE.md §12.1
// Tier 1: reverse the question
// Tier 2: reframe / decompose
// Tier 3: concept reminder (no values)

export interface TieredHint {
  /**
   * 1..3 are template-generated by `generateTieredHints()` below.
   * Tier 4 (v1.4.5) is a fully-worked **parallel problem** with
   * different numbers, sourced from `lib/eke/parallel-problems.ts` and
   * assembled by `EkeEngine.nextHint()`. It is never generated here.
   */
  tier: 1 | 2 | 3 | 4;
  content: string;
  isRevealed: boolean;
  timestamp: number;
}

const TIER_1: string[] = [
  "What's the very first thing you'd write down to start this?",
  "Can you say in your own words what the problem is asking?",
  "What information do you already know, and what are you trying to find?",
  "Have you seen anything like this before? What did you do then?",
];

const TIER_2: string[] = [
  "Could you break this into two smaller problems?",
  "Try working backwards — what would the final step look like?",
  "What's the relationship between the values given?",
  "What if you simplified one piece first and then came back?",
];

const TIER_3: string[] = [
  "This belongs to the family of problems where we isolate the variable. Does that help?",
  "Remember the order in which operations are applied — does that change your approach?",
  "Substitution and elimination are the two main tools here. Which fits better?",
  "Look for what stays constant and what changes — that often points to the method.",
];

function pick(arr: string[]): string {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function generateTieredHints(): TieredHint[] {
  const now = Date.now();
  return [
    { tier: 1, content: pick(TIER_1), isRevealed: false, timestamp: now },
    { tier: 2, content: pick(TIER_2), isRevealed: false, timestamp: now },
    { tier: 3, content: pick(TIER_3), isRevealed: false, timestamp: now },
  ];
}

export function revealNext(hints: TieredHint[]): TieredHint[] {
  const idx = hints.findIndex((h) => !h.isRevealed);
  if (idx === -1) return hints;
  const next = [...hints];
  next[idx] = { ...next[idx], isRevealed: true, timestamp: Date.now() };
  return next;
}

// Validator: hint must not contain a value present in the answer key.
export function hintContainsAnswer(hint: string, answer: string): boolean {
  const h = hint.toLowerCase();
  const a = answer.toLowerCase();
  if (a.length > 2 && h.includes(a)) return true;
  const numsInHint = (h.match(/\d+/g) || []) as string[];
  const numsInAnswer = (a.match(/\d+/g) || []) as string[];
  return numsInAnswer.some((n) => numsInHint.includes(n));
}
