// ─────────────────────────────────────────────────────────────────────────────
// tests/unit/passkey.test.ts
//
// v1.4.11 — End-to-end tests for the WebAuthn passkey path.
//
// Strategy
// ────────
// happy-dom does not implement WebAuthn. We do NOT add a polyfill (that
// would mean we test the polyfill, not the real Web platform). Instead,
// every test:
//
//   1. Generates a real ECDSA P-256 keypair via SubtleCrypto.
//   2. Synthesises WebAuthn-shaped responses around that keypair —
//      authenticatorData, clientDataJSON, attestationObject built by hand.
//   3. Injects a fake `navigator.credentials` via __setCredentialsForTesting.
//   4. Drives the production code paths: enrolPasskey → signPayload(...,
//      {keySource: "passkey"}) → verifyEnvelope.
//
// What this proves on every CI run:
//   • The CBOR / COSE parser accepts authenticator-shaped output.
//   • The DER → raw r||s converter handles real DER signatures.
//   • The verifier replays the WebAuthn signed-bytes formula correctly.
//   • Every honesty rule (challenge binding, type=webauthn.get, no
//     silent fallback) is enforced by the verifier.
// ─────────────────────────────────────────────────────────────────────────────

import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  PasskeyError,
  __setCredentialsForTesting,
  clearEnrolment,
  enrolPasskey,
  getEnrolment,
  isPasskeySupported,
  parseAuthenticatorData,
  derToRawEcdsaP256,
} from "@/lib/crypto/passkey";
import { signPayload, verifyEnvelope } from "@/lib/crypto/signing";
import { encodeCoseKey } from "@/lib/crypto/cbor-min";

const STORAGE_KEY = "evenkeel.passkey.enrolment.v1";

beforeEach(() => {
  if (typeof window !== "undefined") {
    window.localStorage.removeItem(STORAGE_KEY);
  }
  __setCredentialsForTesting(null);
});

afterEach(() => {
  __setCredentialsForTesting(null);
  clearEnrolment();
});

// ─── Test fixtures: generate-and-wrap a real ECDSA P-256 keypair ─────────────

interface PasskeyFixture {
  /** Real, generated by SubtleCrypto — this is what really signs. */
  keyPair: CryptoKeyPair;
  /** Raw 32-byte X coordinate of the public key. */
  x: Uint8Array;
  /** Raw 32-byte Y coordinate of the public key. */
  y: Uint8Array;
  /** Stable random credentialId we hand back from the fake authenticator. */
  credentialId: Uint8Array;
}

async function makeFixture(): Promise<PasskeyFixture> {
  const subtle = window.crypto.subtle;
  const keyPair = (await subtle.generateKey(
    { name: "ECDSA", namedCurve: "P-256" },
    true,
    ["sign", "verify"],
  )) as CryptoKeyPair;
  const jwk = await subtle.exportKey("jwk", keyPair.publicKey);
  const x = b64urlToBytes(jwk.x as string);
  const y = b64urlToBytes(jwk.y as string);
  const credentialId = window.crypto.getRandomValues(new Uint8Array(32));
  return { keyPair, x, y, credentialId };
}

/** RP ID hash matching the constant used inside `passkey.ts`. */
async function rpIdHashFor(rpId: string): Promise<Uint8Array> {
  const buf = await window.crypto.subtle.digest(
    "SHA-256",
    new TextEncoder().encode(rpId),
  );
  return new Uint8Array(buf);
}

/** Build a synthetic authenticatorData blob with the AT (attested) flag set. */
async function makeAttestedAuthData(fx: PasskeyFixture): Promise<Uint8Array> {
  const rpHash = await rpIdHashFor("evenkeel.local");
  const flags = 0x41; // UP | AT
  const signCount = new Uint8Array([0, 0, 0, 1]);
  const aaguid = new Uint8Array(16); // zeros
  const credIdLen = new Uint8Array([0, fx.credentialId.length]);
  const cose = encodeCoseKey([
    [1, 2],
    [3, -7],
    [-1, 1],
    [-2, fx.x],
    [-3, fx.y],
  ]);
  const out = new Uint8Array(
    rpHash.length + 1 + 4 + 16 + 2 + fx.credentialId.length + cose.length,
  );
  let p = 0;
  out.set(rpHash, p); p += rpHash.length;
  out[p++] = flags;
  out.set(signCount, p); p += 4;
  out.set(aaguid, p); p += 16;
  out.set(credIdLen, p); p += 2;
  out.set(fx.credentialId, p); p += fx.credentialId.length;
  out.set(cose, p);
  return out;
}

/** Build a synthetic authenticatorData blob WITHOUT the AT flag (for assertions). */
async function makeAssertionAuthData(): Promise<Uint8Array> {
  const rpHash = await rpIdHashFor("evenkeel.local");
  const flags = 0x05; // UP | UV (no AT)
  const signCount = new Uint8Array([0, 0, 0, 2]);
  const out = new Uint8Array(rpHash.length + 1 + 4);
  out.set(rpHash, 0);
  out[32] = flags;
  out.set(signCount, 33);
  return out;
}

/** Build the attestationObject CBOR ({fmt: "none", attStmt: {}, authData: bytes}). */
function encodeAttestationObject(authData: Uint8Array): Uint8Array {
  // Hand-encode a 3-key CBOR map. Map header (3 entries):
  //   0xa3
  //   key "fmt"   text(3) -> 0x63 'f' 'm' 't'
  //   value "none" text(4) -> 0x64 'n' 'o' 'n' 'e'
  //   key "attStmt" text(7) -> 0x67 'a' 't' 't' 'S' 't' 'm' 't'
  //   value {}    map(0) -> 0xa0
  //   key "authData" text(8) -> 0x68 'a' 'u' 't' 'h' 'D' 'a' 't' 'a'
  //   value bstr(authData)  -> bstr-header || bytes
  const out: number[] = [0xa3];
  out.push(0x63, 0x66, 0x6d, 0x74);             // "fmt"
  out.push(0x64, 0x6e, 0x6f, 0x6e, 0x65);       // "none"
  out.push(0x67, 0x61, 0x74, 0x74, 0x53, 0x74, 0x6d, 0x74); // "attStmt"
  out.push(0xa0);                                // {}
  out.push(0x68, 0x61, 0x75, 0x74, 0x68, 0x44, 0x61, 0x74, 0x61); // "authData"
  // bstr header for authData
  if (authData.length < 24) {
    out.push(0x40 | authData.length);
  } else if (authData.length < 0x100) {
    out.push(0x58, authData.length);
  } else {
    out.push(0x59, (authData.length >> 8) & 0xff, authData.length & 0xff);
  }
  for (let i = 0; i < authData.length; i++) out.push(authData[i]!);
  return new Uint8Array(out);
}

/** ECDSA-sign `bytes` with `privateKey`; returns raw DER as WebAuthn would. */
async function signDer(privateKey: CryptoKey, bytes: Uint8Array): Promise<Uint8Array> {
  // SubtleCrypto only emits raw IEEE-P1363; WebAuthn emits DER. Convert.
  const raw = await window.crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    privateKey,
    bufferOf(bytes),
  );
  return rawToDer(new Uint8Array(raw));
}

/** Inverse of derToRawEcdsaP256, for synthesising WebAuthn fixtures. */
function rawToDer(raw: Uint8Array): Uint8Array {
  if (raw.length !== 64) throw new Error("expected 64-byte raw ECDSA signature");
  const r = stripLeadingZeroes(raw.slice(0, 32));
  const s = stripLeadingZeroes(raw.slice(32, 64));
  // DER INTEGER must have leading 0x00 if high bit is set.
  const rWithSign = (r[0]! & 0x80) !== 0 ? prepend0(r) : r;
  const sWithSign = (s[0]! & 0x80) !== 0 ? prepend0(s) : s;
  const inner =
    Uint8Array.from([0x02, rWithSign.length, ...rWithSign, 0x02, sWithSign.length, ...sWithSign]);
  return Uint8Array.from([0x30, inner.length, ...inner]);
}

function stripLeadingZeroes(bs: Uint8Array): Uint8Array {
  let i = 0;
  while (i < bs.length - 1 && bs[i] === 0x00) i++;
  return bs.slice(i);
}
function prepend0(bs: Uint8Array): Uint8Array {
  const out = new Uint8Array(bs.length + 1);
  out[0] = 0x00;
  out.set(bs, 1);
  return out;
}

/** Build a fake `navigator.credentials`-compatible object backed by `fx`. */
function fakeCredentialsFor(fx: PasskeyFixture): {
  create: (opts: { publicKey: unknown }) => Promise<unknown>;
  get: (opts: { publicKey: unknown }) => Promise<unknown>;
} {
  return {
    async create() {
      const authData = await makeAttestedAuthData(fx);
      const attObj = encodeAttestationObject(authData);
      return {
        rawId: fx.credentialId.buffer.slice(0),
        response: { attestationObject: attObj.buffer.slice(0) },
      };
    },
    async get(opts) {
      // The production code passes the SHA-256 of the canonical payload
      // as the challenge. The browser stuffs that into clientDataJSON.
      const pk = (opts.publicKey as { challenge: ArrayBuffer }).challenge;
      const challengeBytes = new Uint8Array(pk);
      const clientDataJSON = new TextEncoder().encode(
        JSON.stringify({
          type: "webauthn.get",
          challenge: bytesToB64url(challengeBytes),
          origin: "https://evenkeel.local",
        }),
      );
      const authData = await makeAssertionAuthData();
      const cdHash = await window.crypto.subtle.digest(
        "SHA-256",
        bufferOf(clientDataJSON),
      );
      const signedBytes = concat(authData, new Uint8Array(cdHash));
      const sigDer = await signDer(fx.keyPair.privateKey, signedBytes);
      return {
        rawId: fx.credentialId.buffer.slice(0),
        response: {
          authenticatorData: authData.buffer.slice(0),
          clientDataJSON: clientDataJSON.buffer.slice(0),
          signature: sigDer.buffer.slice(0),
        },
      };
    },
  };
}

// ─── Helpers (locally scoped to keep tests self-contained) ──────────────────

function bufferOf(bytes: Uint8Array): ArrayBuffer {
  const copy = new Uint8Array(new ArrayBuffer(bytes.byteLength));
  copy.set(bytes);
  return copy.buffer;
}
function concat(a: Uint8Array, b: Uint8Array): Uint8Array {
  const out = new Uint8Array(a.length + b.length);
  out.set(a, 0);
  out.set(b, a.length);
  return out;
}
function b64urlToBytes(input: string): Uint8Array {
  const pad = input.length % 4 === 0 ? "" : "=".repeat(4 - (input.length % 4));
  const b64 = (input + pad).replace(/-/g, "+").replace(/_/g, "/");
  const binary =
    typeof atob !== "undefined"
      ? atob(b64)
      : Buffer.from(b64, "base64").toString("binary");
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}
function bytesToB64url(bytes: Uint8Array): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]!);
  const b64 =
    typeof btoa !== "undefined"
      ? btoa(bin)
      : Buffer.from(bin, "binary").toString("base64");
  return b64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

// ─── Tests ──────────────────────────────────────────────────────────────────

describe("passkey: feature detection", () => {
  it("isPasskeySupported returns a boolean (no throws on call)", () => {
    expect(typeof isPasskeySupported()).toBe("boolean");
  });
});

describe("passkey: derToRawEcdsaP256 (signature converter)", () => {
  it("round-trips a real DER signature", async () => {
    const kp = (await window.crypto.subtle.generateKey(
      { name: "ECDSA", namedCurve: "P-256" },
      true,
      ["sign", "verify"],
    )) as CryptoKeyPair;
    const message = new TextEncoder().encode("hello");
    const rawSig = new Uint8Array(
      await window.crypto.subtle.sign(
        { name: "ECDSA", hash: "SHA-256" },
        kp.privateKey,
        bufferOf(message),
      ),
    );
    const derSig = rawToDer(rawSig);
    const recovered = derToRawEcdsaP256(derSig);
    expect(Array.from(recovered)).toEqual(Array.from(rawSig));
  });

  it("rejects non-DER input", () => {
    expect(() => derToRawEcdsaP256(new Uint8Array([0, 1, 2, 3])))
      .toThrow(PasskeyError);
  });
});

describe("passkey: parseAuthenticatorData", () => {
  it("rejects truncated buffers", () => {
    expect(() => parseAuthenticatorData(new Uint8Array(10)))
      .toThrow(PasskeyError);
  });

  it("parses the AT-flagged shape produced by makeAttestedAuthData", async () => {
    const fx = await makeFixture();
    const authData = await makeAttestedAuthData(fx);
    const parsed = parseAuthenticatorData(authData);
    expect(parsed.attested).toBeDefined();
    expect(Array.from(parsed.attested!.credentialId)).toEqual(Array.from(fx.credentialId));
  });

  it("returns no `attested` block when the AT flag is clear", async () => {
    const authData = await makeAssertionAuthData();
    const parsed = parseAuthenticatorData(authData);
    expect(parsed.attested).toBeUndefined();
  });
});

describe("passkey: enrol → sign → verify happy path", () => {
  it("end-to-end round-trips a passkey-signed envelope", async () => {
    const fx = await makeFixture();
    __setCredentialsForTesting(fakeCredentialsFor(fx));

    const enrolment = await enrolPasskey();
    expect(enrolment.credentialIdB64url.length).toBeGreaterThan(0);
    expect(enrolment.spkiB64url.length).toBeGreaterThan(0);

    // localStorage-backed
    const persisted = getEnrolment();
    expect(persisted?.credentialIdB64url).toBe(enrolment.credentialIdB64url);

    const payload = { hello: "world", n: 42 };
    const env = await signPayload(payload, { keySource: "passkey" });
    expect(env.keyType).toBe("passkey-derived");
    expect(env.webauthn).toBeDefined();
    expect(env.webauthn?.credentialIdB64url).toBe(enrolment.credentialIdB64url);

    const ok = await verifyEnvelope(env);
    expect(ok).toBe(true);
  });
});

describe("passkey: verifier rejects tampering", () => {
  it("rejects a tampered payload", async () => {
    const fx = await makeFixture();
    __setCredentialsForTesting(fakeCredentialsFor(fx));
    await enrolPasskey();
    const env = await signPayload({ hello: "world" }, { keySource: "passkey" });
    const tampered = { ...env, payload: { hello: "WORLD" } };
    expect(await verifyEnvelope(tampered)).toBe(false);
  });

  it("rejects a tampered authenticatorData", async () => {
    const fx = await makeFixture();
    __setCredentialsForTesting(fakeCredentialsFor(fx));
    await enrolPasskey();
    const env = await signPayload({ x: 1 }, { keySource: "passkey" });
    const flipped = b64urlToBytes(env.webauthn!.authenticatorDataB64url);
    flipped[0] ^= 0x01;
    const tampered = {
      ...env,
      webauthn: {
        ...env.webauthn!,
        authenticatorDataB64url: bytesToB64url(flipped),
      },
    };
    expect(await verifyEnvelope(tampered)).toBe(false);
  });

  it("rejects a clientDataJSON whose challenge does not match the payload digest", async () => {
    const fx = await makeFixture();
    __setCredentialsForTesting(fakeCredentialsFor(fx));
    await enrolPasskey();
    const env = await signPayload({ x: 1 }, { keySource: "passkey" });
    const fake = new TextEncoder().encode(
      JSON.stringify({
        type: "webauthn.get",
        challenge: "AAAA", // wrong
        origin: "https://evenkeel.local",
      }),
    );
    const tampered = {
      ...env,
      webauthn: {
        ...env.webauthn!,
        clientDataJsonB64url: bytesToB64url(fake),
      },
    };
    expect(await verifyEnvelope(tampered)).toBe(false);
  });

  it("rejects clientDataJSON.type that is not webauthn.get", async () => {
    const fx = await makeFixture();
    __setCredentialsForTesting(fakeCredentialsFor(fx));
    await enrolPasskey();
    const env = await signPayload({ x: 1 }, { keySource: "passkey" });
    const cdj = JSON.parse(
      new TextDecoder().decode(b64urlToBytes(env.webauthn!.clientDataJsonB64url)),
    );
    cdj.type = "webauthn.create";
    const swapped = new TextEncoder().encode(JSON.stringify(cdj));
    const tampered = {
      ...env,
      webauthn: {
        ...env.webauthn!,
        clientDataJsonB64url: bytesToB64url(swapped),
      },
    };
    expect(await verifyEnvelope(tampered)).toBe(false);
  });
});

describe("passkey: failure modes are typed, not silent", () => {
  it("signing without an enrolment throws PasskeyError {no_enrolment}", async () => {
    const fx = await makeFixture();
    __setCredentialsForTesting(fakeCredentialsFor(fx));
    // Do NOT enrol.
    await expect(
      signPayload({ x: 1 }, { keySource: "passkey" }),
    ).rejects.toMatchObject({ name: "PasskeyError", code: "no_enrolment" });
  });

  it("user-cancelled enrolment surfaces as PasskeyError {cancelled}", async () => {
    __setCredentialsForTesting({
      async create() {
        const e = new Error("user denied");
        e.name = "NotAllowedError";
        throw e;
      },
      async get() {
        throw new Error("not used");
      },
    });
    await expect(enrolPasskey()).rejects.toMatchObject({
      name: "PasskeyError",
      code: "cancelled",
    });
  });

  it("user-cancelled signing surfaces as PasskeyError {cancelled}", async () => {
    const fx = await makeFixture();
    __setCredentialsForTesting(fakeCredentialsFor(fx));
    await enrolPasskey();
    // Now swap to a fake whose .get rejects with NotAllowedError
    __setCredentialsForTesting({
      async create() {
        throw new Error("not used");
      },
      async get() {
        const e = new Error("user denied");
        e.name = "NotAllowedError";
        throw e;
      },
    });
    await expect(
      signPayload({ x: 1 }, { keySource: "passkey" }),
    ).rejects.toMatchObject({ name: "PasskeyError", code: "cancelled" });
  });
});

describe("passkey: backwards compatibility with v1.4.10 envelopes", () => {
  it("v1.4.10-shaped envelopes (no keyType, no webauthn) verify unchanged", async () => {
    const env = await signPayload({ legacy: true });
    expect(env.webauthn).toBeUndefined();
    // Default keyType is now "session-demo" but the optional field
    // doesn't break verification when omitted.
    expect(env.keyType).toBe("session-demo");
    expect(await verifyEnvelope(env)).toBe(true);

    // An envelope built without keyType (simulating v1.4.10 on disk)
    // must still verify.
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { keyType: _kt, ...legacy } = env;
    expect(await verifyEnvelope(legacy as typeof env)).toBe(true);
  });
});
